[project]
name = "apex-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dbt-core>=1.10.13",
    "dbt-snowflake>=1.10.2",
]
