name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - staging
      - main
    paths:
      - 'infra/snowflake/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || (github.ref_name == 'staging' && 'staging' || 'dev') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Set up Snowflake private key
        run: |
          mkdir -p ~/.ssh
          printf '%s/n' "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.ssh/snowflake_key.p8
          chmod 600 ~/.ssh/snowflake_key.p8

      - name : Verify key + DNS 
        run: |
          grep --q "BEGING PRIVATE KEY" ~/.ssh/snowflake_key.p8 || (echo "No PEM header && exit 1")
          echo "Resolving Swnoflake host..."
          nslookup ${{ secrets.SNOWFLAKE_ACCOUNT }}.snowflakecomputing.com || (echo "Bad Snowflake_account value && exit 1")
          

      - name: Determine environment
        id: env
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "staging" ]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init
        timeout-minutes: 5
        working-directory: infra/snowflake
        env:
          TF_VAR_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          TF_VAR_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          TF_VAR_etl_service_account_password: ${{ secrets.ETL_SERVICE_ACCOUNT_PASSWORD }}
          TF_LOG: DEBUG
          TF_LOG_PATH: teraform_init.log        
        run: terraform init

      - name: Select Terraform Workspace
        working-directory: infra/snowflake
        run: |
          terraform workspace select ${{ steps.env.outputs.environment }} || terraform workspace new ${{ steps.env.outputs.environment }}

      - name: Terraform Plan
        working-directory: infra/snowflake
        env:
          TF_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          TF_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          TF_VAR_etl_service_account_password: ${{ secrets.ETL_SERVICE_ACCOUNT_PASSWORD }}
        run: |
          terraform plan -var="environment=${{ steps.env.outputs.environment }}" -out=tfplan

      - name: Terraform Apply
        working-directory: infra/snowflake
        env:
          TF_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          TF_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          TF_VAR_etl_service_account_password: ${{ secrets.ETL_SERVICE_ACCOUNT_PASSWORD }}
        run: terraform apply -auto-approve tfplan

      - name: Notify on failure
        if: failure()
        run: echo "Terraform deployment failed! Check logs."
